import React from 'react';

const FAQs = () => {
  const faqData = [
    {
      question: "What is Notion-Avatar-Maker?",
      answer: "Notion-Avatar-Maker is a tool that allows you to create custom Notion-style avatars for your social media profiles. You can customize the hair, eyes, mouth, head, beard, accessories, and facial hair of your avatar."
    },
    {
      question: "What is a Notion-Style-Avatar?",
      answer: "A Notion avatar is a custom image that you can use to represent yourself on social media. You can use Notion-Avatar-Maker to create a custom Notion-style avatar for your socials."
    },
    {
      question: "Is Notion-Avatar-Maker free?",
      answer: "Yes, Notion-Avatar-Maker is free to use. You can create and download your custom Notion-style avatar without paying anything."
    },
    {
      question: "Can I share the avatars created with Notion-Avatar-Maker on social media?",
      answer: "Yes, the avatars generated by Notion-Avatar-Maker are yours to use as you wish, including sharing them on social media platforms. You have full rights to use and distribute the avatars you create for any purpose, personal or commercial."
    },
    {
      question: "What file formats can I download my avatar in?",
      answer: "You can download your custom Notion-style avatar in PNG or SVG formats from Notion-Avatar-Maker."
    },
    {
      question: "Is there a limit to how many avatars I can create?",
      answer: "There are no limits on the number of avatars you can create using Notion-Avatar-Maker. Feel free to generate as many as you need!"
    },
    {
      question: "Are there any plans for future features or updates?",
      answer: "We are constantly working on improving Notion-Avatar-Maker. Stay tuned for future updates, including new customization options and features!"
    }
  ];

  return (
    <div className="py-12 bg-gray-50">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <h2 className="text-3xl font-extrabold text-gray-900 mb-8 text-center">
          Notion-Avatar-Maker FAQs
        </h2>
        <div className="space-y-8">
          {faqData.map((faq, index) => (
            <div key={index} className="bg-white shadow-sm rounded-lg overflow-hidden">
              <div className="px-6 py-4">
                <h3 className="text-lg font-medium text-gray-900 mb-2">
                  {faq.question}
                </h3>
                <p className="text-gray-500">
                  {faq.answer}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default FAQs;